import type { Metadata } from "next";
import { Oswald, Roboto } from "next/font/google";
import "./globals.css";
import { ToastContainer, toast } from 'react-toastify';
import { getAllCategories } from "@/apiCalls/categoriesCalls";
import { Navbar } from "@/componant/Navbar/Navbar";
import Footer from "@/componant/Footer/Footer";

 export const getOswald = Oswald
({
  variable: "--font-get-oswald",
  subsets: ["latin"],
});

 export const getRoboto = Roboto({
  variable: "--font-get-robert",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  const allCategories = await getAllCategories(1);
  return (
    <html lang="en"  className={`${getOswald.variable} ${getRoboto.variable} `}>
      
      <body
        className={` antialiased `}
      >
        <Navbar initialCategories={allCategories.categories}/>
        {children}
      <Footer/>
          <ToastContainer />
      </body>
      
    </html>
  );
}
